[profile.default]
src = 'src'                                                
test = 'test'                                                 
out = 'out'                                                 
libs = ['lib']                                                
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]   
